workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - 1575214258@qq.com # 替换为你的邮箱
