workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter build iOS
        script: |
          # 使用 build ipa 代替 build ios，这是目前 Flutter 推荐的打包方式
          # 如果你配置了代码签名，请移除 --no-codesign
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
      - build/ios/archive/*.xcarchive
    publishing:
      email:
        recipients:
          - 1575214258@qq.com # 替换为你的邮箱
